version: '3.3'

networks:
  prometheus_net:
    driver: overlay
    driver_opts:
      encrypted: "true"
    attachable: true
    labels:
      - "com.docker.ucp.access.label=/Shared/DevTeams/Yoda/Prod"

volumes:
  prometheus-data: {}
  grafana-data: {}
  grafana-plugins: {}

configs:
  prometheus.yml:
    external: true

secrets:
  grafana_admin_pass:
    external: true

services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - prometheus_net
    ports:
      - 9090:9090
    labels:
      - "com.docker.ucp.access.label=/Shared/DevTeams/Yoda/Prod"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
    volumes:
      - prometheus-data:/prometheus/data
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "com.docker.ucp.access.label=/Shared/DevTeams/Yoda/Prod"
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux
    depends_on:
      - cadvisor
      - node-exporter

  cadvisor:
    image:  google/cadvisor:latest
    networks:
      - prometheus_net
    ports:
      - 8080:8080
    labels:
      - "com.docker.ucp.access.label=/Shared/DevTeams/Yoda/Prod"
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    deploy:
      mode: global
      labels:
        - "com.docker.ucp.access.label=/Shared/DevTeams/Yoda/Prod"

  pushgateway:
    image: prom/pushgateway:latest
    networks:
      - prometheus_net
    ports:
      - 9091:9091
    labels:
      - "com.docker.ucp.access.label=/Shared/DevTeams/Yoda/Prod"
    deploy:
      mode: global
      labels:
        - "com.docker.ucp.access.label=/Shared/DevTeams/Yoda/Prod"

  node-exporter:
    image: prom/node-exporter:latest
    networks:
      - prometheus_net
    ports:
      - 9100:9100
    labels:
      - "com.docker.ucp.access.label=/Shared/DevTeams/Yoda/Prod"
    volumes:
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    deploy:
      mode: global
      labels:
        - "com.docker.ucp.access.label=/Shared/DevTeams/Yoda/Prod"

  grafana:
    image: grafana/grafana:latest
    networks:
      - prometheus_net
    ports:
      - 3000:3000
    labels:
      - "com.docker.ucp.access.label=/Shared/DevTeams/Yoda/Prod"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-plugins:/var/lib/grafana/plugins
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_pass
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "com.docker.ucp.access.label=/Shared/DevTeams/Yoda/Prod"
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux
    depends_on:
      - prometheus
      - cadvisor

