version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./data/etc/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus:rw
    depends_on:
      - cadvisor
    deploy:
      mode: replicated
      replicas: 1


  cadvisor:
    image:  google/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      update_config:
        parallelism: 3
        monitor: 2m
        max_failure_ratio: 0.3
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3


  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - 9091:9091

  node-exporter:
    image: prom/node-exporter:latest
    ports:
    - 9100:9100
    volumes:
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /proc:/host/proc:ro
    deploy:
      mode: global


  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana:rw
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=letmein
    depends_on:
      - prometheus
      - cadvisor
    deploy:
      mode: replicated
      replicas: 1
