global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - prometheus_cadvisor:8080
          - prometheus_prometheus:9090
          - prometheus_node-exporter:9100
          - prometheus_pushgateway:9091

  - job_name: docker
    scrape_interval: 5s
    static_configs:
      - targets:
        - 127.0.0.1:9323 
